### ISSUE TITLE
codfreq without docker?

### ISSUE THREAD

**Issue by CEJ-R** [hivdb/codfreq#8]
Hi!

We want to run codfreq on out HCP, where we are forced to use singularity for containerization instead of docker. I've tried to download the dockerimage `hivdb/codfreq-runner:latest` through singularity, as suggested elsewhere: https://docs.sylabs.io/guides/2.6/user-guide/singularity_and_docker.html However, this hasn't worked and appears to create an unusable image.

Do you have any suggestions on how we can get this to run without docker? Would it be possible to just run the scripts on their own, maybe? Where would I start, in that case?

Thank you in advance!

**Comment by philiptzou** [comment]
Hi @CEJ-R! Have you tried built Singularity image from the Dockerfile? Here're a few answers I found on StackOverflow that might be helpful: https://stackoverflow.com/a/60316979/2644759.

In addition, this is our Dockerfile: https://github.com/hivdb/codfreq/blob/main/Dockerfile. It looks like you can use spython to convert it to a Singularity.def. The Dockerfile is also a description for people who want to run the program on their own since it listed all the dependencies and their versions.

**Comment by CEJ-R** [comment]
Hi again @philiptzou 

Just wanted to say that we managed to get this installed and that it seems to work (although I have yet to validate it). However I wanted to give you a heads-up that the README is out-of-date with the flags that codfreq currently has. For instance, isn't `-d` available anymore, which caused some momentary confusion:
```
fastq2codfreq --help
Usage: fastq2codfreq [OPTIONS] WORKDIR

Options:
  -p, --program [bowtie2|minimap2]
                                  [required]
  -r, --profile FILENAME          [required]
  --log-format [text|json]        [default: text]
  --enable-profiling / --disable-profiling
                                  Enable/disable cProfile
  --autopairing / --no-autopairing
                                  Enable/disable automatical FASTQ pairing
                                  algorithm
  --workers INTEGER               Number of sub-process workers to be used
                                  [default: 112]
  --help                          Show this message and exit.

```
Thanks for the help! Hopefully I can take it from here!

**Comment by philiptzou** [comment]
Hello @CEJ-R! Sorry for not responding in time. I'm glad that you figured it out!

About the README document, it's not exactly true since the command you used is designed to be an internal command for this wrapper bash script: https://github.com/hivdb/codfreq/blob/main/bin-wrapper/align-all-docker. In our REAME this bash script is referred as the "fastq2codfreq" command.

However, obviously you can not use this bash script since it is designed for Docker. However, if you'd like to contribute a PR of documentation and scripts for Singularity, I will add it to the repository with my gratitude.

**Comment by MarcNiebel** [comment]
Hello @CEJ-R,
Would you be willing to posting your singularity definition file which you created with spython because I am repeatedly getting the error 
`FATAL:   While performing build: conveyor failed to get: GET https://index.docker.io/v2/library/builder/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/builder Type:repository]]` when using the `singularity build `function.
